version: '3.4'

services:
  catalogdb:
   image: mongo

  discountdb:
   image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  